name: get-vcn

on:
  push:
    branches: [main]

jobs:
  get-latest-vcn-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.review.commit_id }}

      - name: Download VCN
        uses: codenotary/vcn-github-action@main
        with:
          standard_usage: false
        
      - name: Test vcn binary is available
        run: ls -alrht; vcn --help;
        shell: bash

